puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Dan"
puts "Hadi"
puts "Craig"
puts "Andrew"
puts "Andrew"
puts "Steve"
puts "Tim"
puts "Colin"
puts "James"
puts "Andrew"
puts "Bernard"
puts "Zeeshan"
puts "Fadie"
puts "Sean"
puts "Pablo"
puts "Alex"
puts "Nicole"
puts "Sandrine"
puts "Yvette"
puts "Denise"
puts "Victoria"
puts "Camilla"
puts "Ella"
puts "Ana"
puts "Anna"
puts "Rachel"
puts "Elena"
puts "Karin"

print "Overall, we have "
print 28
puts " great students"